return {
  -- "saghen/blink.cmp",
  -- opts = {
  --   file_selector = {
  --     provider = "fzf",
  --     provider_opts = {},
  --   },
  --   sources = {
  --     compat = {
  --       "avante_commands",
  --       "avante_mentions",
  --       "avente_files",
  --     },
  --     providers = {
  --       avante_commands = {
  --         name = "avante_commands",
  --         module = "blink.compat.source",
  --         score_offset = 90, -- show at a higher priority than lsp
  --         opts = {},
  --       },
  --       avante_files = {
  --         name = "avante_commands",
  --         module = "blink.compat.source",
  --         score_offset = 100, -- show at a higher priority than lsp
  --         opts = {},
  --       },
  --       avante_mentions = {
  --         name = "avante_mentions",
  --         module = "blink.compat.source",
  --         score_offset = 1000, -- show at a higher priority than lsp
  --         opts = {},
  --       },
  --     },
  --   },
  -- },
}
