vim.api.nvim_create_autocmd("User", {
  pattern = "TSUpdate",
  callback = function()
    require("nvim-treesitter.parsers").comment = {
      install_info = {
        url = "https://github.com/OXY2DEV/tree-sitter-comment",
        branch = "main",

        -- Also installs the query files(*syntax highlighting*), Only for the `main` branch of `nvim-treesitter`.
        queries = "queries/",
      },
    }
  end,
})

return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = { "OXY2DEV/markview.nvim" },
  lazy = false,
  opts = {
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "hcl",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "latex",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "ninja",
      "ocaml",
      "printf",
      "python",
      "query",
      "regex",
      "ron",
      "rst",
      "rust",
      "scss",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "typst",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
      "zig",
    },
  },
}
